catalogo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.catalogo, name = "catalogo"),
    path('obras/registrar', views.registrar_obra, name = "registrar_obra"),
    path('obras/<int:obra_id>', views.detalles, name = "obra"),
    path('obras/<int:obra_id>/editar', views.editar_obra, name = "editar_obra"),
    path('obras/<int:obra_id>/eliminar', views.eliminar_obra, name="eliminar_obra"),
    path('add_to_carrito/', views.add_to_carrito, name="add_to_carrito")
]

pagina_obras/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from core import views

urlpatterns = [
    path('', views.home, name = 'home'),
    path('catalogo/', include("catalogo.urls")),
    path('checkout/', include("checkout.urls")),
    path('usuarios/', include("usuarios.urls")),
    path('info/', views.info, name = "info"),
    path('pedidos/', views.pedidos, name = "pedidos"),
    path('restringido/', views.restringido, name = "restringido"),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
import cloudinary.uploader

class Etiqueta(models.Model):
    nombre = models.CharField(max_length = 15, verbose_name = "Nombre")
    descripcion = models.CharField(max_length = 70, default = "", verbose_name = "Descripción")

    created = models.DateTimeField(auto_now = True, verbose_name = "Fecha de creación")
    updated = models.DateTimeField(auto_now_add = True, verbose_name = "Fecha de edición")

    class Meta:
        verbose_name = "Etiqueta"
        verbose_name_plural = "Etiquetas"

    def __str__(self): return self.nombre

obras_medios = [
    ("Lienzo", "Lienzo"),
    ("Mural", "Mural"),
    ("Impresiones", "Impresiones")
]

obras_estados = [
    ("Disponible", "Disponible"),
    ("Agotado", "Agotado"),
    ("Reservado", "Reservado")
]
class Obra(models.Model):
    titulo = models.CharField(max_length = 50, verbose_name = "Titulo")

    imagen = models.ImageField(upload_to = "obras/", null = True, blank = True, verbose_name = "Imagen")
    imagen_url = models.URLField(blank=True, null=True)

    medio = models.CharField(max_length = 50, default = "Lienzo", choices = obras_medios, verbose_name = "Medio de Obra")
    etiquetas = models.ManyToManyField(Etiqueta, verbose_name = "etiquetas")
    precio = models.IntegerField(validators=[MinValueValidator(0)], verbose_name = "Precio")
    estado = models.CharField(max_length = 50, default = "Normal", choices = obras_estados, verbose_name = "Estado del producto")

    created = models.DateTimeField(auto_now = True, verbose_name = "Fecha de creación")
    updated = models.DateTimeField(auto_now_add = True, verbose_name = "Última vez editado")

    class Meta:
        verbose_name = "Obra"
        verbose_name_plural = "Obras"

    def save(self, *args, **kwargs):
        # Si se cargó una imagen local nueva:
        if self.imagen:
            upload = cloudinary.uploader.upload(self.imagen)
            self.imagen_url = upload.get("secure_url")   # ← Guardamos solo la URL
            self.imagen = None                   # opcional: ya no la guardas local

        super().save(*args, **kwargs)

    def __str__(self): return self.titulo

fuentes_de_texto = [
    ("base", "base"),
    ("oswald", "oswald")
]

class Publicacion(models.Model):
    descripcion = models.TextField(null = True, blank = True, verbose_name = "Descripción")
    fuente_de_texto = models.CharField(max_length=20, choices=fuentes_de_texto, default="base", verbose_name="Fuente de texto")
    obra = models.ForeignKey(Obra, on_delete=models.CASCADE, verbose_name="Cita de publicación")

    created = models.DateTimeField(auto_now = True, verbose_name = "Fecha de creación")
    updated = models.DateTimeField(auto_now_add = True, verbose_name = "Última vez editado")

    class Meta:
        verbose_name = "publicación"
        verbose_name_plural = "publicaciones"

catalogo/forms.py
from django import forms
from .models import Etiqueta, obras_medios, obras_estados
from django.core.validators import MinValueValidator

class PublicacionForm(forms.Form):
    titulo = forms.CharField(label = "Titulo", required = True, max_length = 50)
    imagen = forms.ImageField(required = True)
    precio = forms.IntegerField(label = "Precio", required = True, validators=[MinValueValidator(1)])
    medio = forms.ChoiceField(choices = [(None, "Selecciona medio de obra")] + obras_medios)
    estado = forms.ChoiceField(choices = [(None, "Selecciona estado del producto")] + obras_estados)
    descripcion = forms.CharField(label = "Descripción", 
        widget=forms.Textarea(attrs={
            "rows": 5,
            "class": "form-control"
        }))
    etiquetas = forms.ModelMultipleChoiceField(queryset = Etiqueta.objects.all(), widget=forms.CheckboxSelectMultiple, required = False)

    def clean_imagen(self):
        img = self.cleaned_data.get("imagen")

        if img.content_type not in ["image/jpeg", "image/png"]:
            raise forms.ValidationError("Solo se aceptan archivos jpeg y png.")

        if img and img.size > 5 * 1024 * 1024:
            raise forms.ValidationError("Capacidad de archivo sobrepasa 5MB.")

        return img
    
class PublicacionEditarForm(forms.Form):
    titulo = forms.CharField(label = "Titulo", required = True, max_length = 50)
    imagen = forms.ImageField(required = False)
    precio = forms.IntegerField(label = "Precio", required = True, validators=[MinValueValidator(1)])
    medio = forms.ChoiceField(choices = [(None, "Selecciona medio de obra")] + obras_medios)
    estado = forms.ChoiceField(choices = [(None, "Selecciona estado del producto")] + obras_estados)
    descripcion = forms.CharField(label = "Descripción", 
        widget=forms.Textarea(attrs={
            "rows": 5,
            "class": "form-control"
        }))
    etiquetas = forms.ModelMultipleChoiceField(queryset = Etiqueta.objects.all(), widget=forms.CheckboxSelectMultiple, required = False)

    def clean_imagen(self):
        img = self.cleaned_data.get("imagen")

        if img is None:
            return None

        if img.content_type not in ["image/jpeg", "image/png"]:
            raise forms.ValidationError("Solo se aceptan archivos jpeg y png.")

        if img and img.size > 5 * 1024 * 1024:
            raise forms.ValidationError("Capacidad de archivo sobrepasa 5MB.")

        return img

catalogo/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, permission_required
from .models import Obra, Publicacion
from django.core.paginator import Paginator
from .forms import PublicacionForm, PublicacionEditarForm

def catalogo(req):
    filtros = {}

    medio = req.GET.get('medio', None)
    lista_medios = [t[0] for t in Obra.medio.field.choices]

    estado = req.GET.get('estado', None)
    lista_estados = [t[0] for t in Obra.estado.field.choices]

    if medio in lista_medios:
        filtros["medio"] = medio
    if estado in lista_estados:
        filtros["estado"] = estado

    obras = Obra.objects.filter(**filtros).order_by("id")
    pag = Paginator(obras, 12)

    page_number = req.GET.get('page') # Se pasa la url que se quiere conseguir, en este caso: ?page=n
    page_obj = pag.get_page(page_number)

    index = page_obj.number - 1  # Índice actual. Paginator.number nos da un número indexeado a 1, no a 0. Se resta para mantener una indexación de 0 para el rango
    max_index = len(pag.page_range) # Consigue la cantidad de paginas en relación con la cantidad de objetos por página
    start_index = max(index - 2, 0)
    end_index = min(index + 3, max_index)
    page_range = pag.page_range[start_index:end_index]

    return render(req, 'catalogo/catalogo.html', {
        "lista_medios": lista_medios,
        "medio_seleccionado": medio,
        "lista_estados": lista_estados,
        "estado_seleccionado": estado,
        "page_obj": page_obj,
        "page_range": page_range
    })

def detalles(req, obra_id):
    obra = Obra.objects.get(id = obra_id)
    publicacion = Publicacion.objects.get(obra__id = obra_id)
    return render(req, 'catalogo/detalles.html', {"obra": obra, "publicacion": publicacion})

@login_required
def add_to_carrito(req):
    if req.method == 'POST':
        obra = req.POST.get('obra')

        product_list = req.session.get("carrito", [])
        if obra not in product_list:
            product_list.append(obra)
            req.session["carrito"] = product_list
    return HttpResponse("")

@permission_required('catalogo.add_obra', login_url="/restringido")
def registrar_obra(req):
    if req.method == 'POST':
        form = PublicacionForm(req.POST, req.FILES)
        if form.is_valid():
            descripcion = form.cleaned_data['descripcion']
            etiquetas = form.cleaned_data['etiquetas']
            obra_creada = Obra.objects.create(
                titulo = form.cleaned_data['titulo'],
                imagen = form.cleaned_data['imagen'],
                medio = form.cleaned_data['medio'],
                estado = form.cleaned_data['estado'],
                precio = form.cleaned_data['precio']
            )
            obra_creada.etiquetas.set(etiquetas)
            obra_creada.save()
            post = Publicacion.objects.create(descripcion = descripcion, obra = obra_creada)
            post.save()
            return redirect(reverse('catalogo'))
    else: 
        form = PublicacionForm()

    return render(req, 'catalogo/registrar_obra.html', {'form': form})

@permission_required('catalogo.change_obra', login_url="/restringido")
def editar_obra(req, obra_id):
    try: 
        obra = Obra.objects.get(id = obra_id)
        post = Publicacion.objects.get(obra__id = obra_id)
    except: 
        return redirect(reverse('restringido'))
    
    if req.method == 'POST':
        form = PublicacionEditarForm(req.POST, req.FILES)
        if form.is_valid():
            post.descripcion = form.cleaned_data['descripcion']
            etiquetas = form.cleaned_data['etiquetas']

            obra.titulo = form.cleaned_data['titulo']
            obra.medio = form.cleaned_data['medio']
            obra.estado = form.cleaned_data['estado']
            obra.precio = form.cleaned_data['precio']
            if form.cleaned_data['imagen']: 
                obra.imagen = form.cleaned_data['imagen']
            else: obra.imagen = None
            obra.etiquetas.set(etiquetas)

            obra.save()
            post.save()
            return redirect(reverse('obra', args=[obra_id]))
    else: 
        form = PublicacionEditarForm(initial = {
            'titulo': obra.titulo,
            'medio': obra.medio,
            'estado': obra.estado,
            'precio': obra.precio,
            'descripcion': post.descripcion,
            'etiquetas': obra.etiquetas.all()
        })

    return render(req, 'catalogo/editar_obra.html', {'form': form, "obra": obra})

@permission_required('catalogo.delete_obra', login_url="/restringido")
def eliminar_obra(req, obra_id):
    try: 
        obra = Obra.objects.get(id = obra_id)
        publicacion = Publicacion.objects.get(obra__id = obra_id)
    except: 
        return redirect(reverse('restringido'))
    if req.method == "POST":
        publicacion.delete()
        obra.delete()
        return redirect(reverse('catalogo'))
    return render(req, "catalogo/eliminar_obra.html", {"obra": obra, "publicacion": publicacion})

catalogo/templates/catalogo/catalogo.html
{% extends 'core/base.html' %}

{% load static %}
{% block contenido %}

<section class="contenido container mb-3 justify-content-center">
    <h2>Catálogo
        {% if perms.catalogo.add_publicacion %}
        <a class="btn btn-primary mb-3" href="{% url 'registrar_obra' %}">Añadir obra</a>
        {% endif %}
    </h2>

    <form method="get" class="mb-4 col-8">
        <div class="row justify-content-center">

            <div class="col-4">
                <select name="medio" class="form-select">
                    <option value="">Buscar por medio</option>
                    {% for medio in lista_medios %}
                        <option value="{{ medio }}" {% if medio_seleccionado == medio %}selected{% endif %}>
                            {{ medio }}
                        </option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-4">
                <select name="estado" class="form-select">
                    <option value="">Buscar por estado</option>
                    {% for estado in lista_estados %}
                        <option value="{{ estado }}" {% if estado_seleccionado == estado %}selected{% endif %}>
                            {{ estado }}
                        </option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-2">
                <button class="btn btn-primary" type="submit">Filtrar</button>
            </div>
        </div>
    </form>

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-3 justify-content-center">

        {% for o in page_obj.object_list %}
        <div class="card mx-1" style="width: 18rem;">
            <a href="{% url 'obra' o.id %}">
                <div class="ratio ratio-1x1">
                    <img class="img-fluid object-fit-cover" src="{{ o.imagen_url }}" alt="obra">
                </div>
            </a>
            <div class="card-body d-flex flex-column justify-content-between">
                <h4 class="card-title text-start">{{ o.titulo }}</h4>
                    <div>
                        <h5 class="card-title text-start">{{ o.precio }}$</h5>
                        <h5 class="card-title text-start text-muted">Estado: {{ o.estado }}</h5>
                        <a href="{% url 'obra' o.id %}" class="btn btn-primary mt-2">Ver producto</a>
                        {% if user.is_authenticated %}
                        <form
                            hx-post="{% url 'add_to_carrito' %}"
                            hx-trigger="submit"
                            hx-swap="none"
                        >
                            {% csrf_token %}
                            <input type="text" name="obra" value="{{ o.id }}" class="d-none">
                            <input
                            {% if user.is_authenticated %}
                            type="submit"
                            {% else %}
                            type="button"
                            {% endif %}
                            value = "Añadir a Carrito"
                            {% if o.estado == 'Disponible' %}
                                class="btn btn-primary mt-2"
                            {% else %}
                                class="btn btn-secondary mt-2"
                                disabled
                            {% endif %}>
                        </form>
                        {% endif %}
                    </div>
            </div>
        </div>
        {% endfor %}
    </div> 

    <nav aria-label="Paginación" class="row mt-5">
            <ul class="pagination justify-content-center">

                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                </li>
                {% else %}
                <li class="page-item disabled"><span class="page-link">Anterior</span></li>
                {% endif %}


                {% for num in page_range %}
                <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endfor %}


                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                </li>
                {% else %}
                <li class="page-item disabled"><span class="page-link">Siguiente</span></li>
                {% endif %}
            </ul>
        </nav>

</section>

<script src="https://unpkg.com/htmx.org@1.9.10"></script>

{% endblock %}

catalogo/templates/catalogo/detalles.html
{% extends 'core/base.html' %}

{% load static %}
{% block contenido %}

<section class="contenido container">
    <div class="row mb-3 justify-content-around">
        <a href="{% url 'catalogo' %}" class="btn btn-secondary col-2">Volver al catálogo</a>
        <div class="col-10"></div>
    </div>
    <div class="row mb-3 justify-content-around">
        <img class="img-fluid col-4" src="{{ obra.imagen_url }}" alt="obra">
        <div class="col-7">
            <h2>{{ obra.titulo }} <span class="text-muted fs-4">ID: {{ obra.id }}</span></h2>
            <h3 class="text-primary">Medio: {{ obra.medio }}</h3>
            <h5 class="text-muted">
                Etiquetas: 
                    {% for e in obra.etiquetas.all %}
                        {{ e.nombre }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
            </h5>

            <hr>

            <h4 class="fs-5 mb-4 {% if publicacion.fuente_de_texto == 'oswald' %}oswald{% endif %}">{{ publicacion.descripcion }}</h4>
            <h3 class="text-success">{{ obra.estado }} | Precio: ${{ obra.precio }}</h3>
            {% if user.is_authenticated %}
            <form
                hx-post="{% url 'add_to_carrito' %}"
                hx-trigger="submit"
                hx-swap="none"
            >
                {% csrf_token %}
                <input type="text" name="obra" value="{{ obra.id }}" class="d-none">
                <input type="submit" class="btn btn-primary mt-2" value="Añadir a Carrito" {% if obra.estado != "Disponible" %} disabled {% endif %}>
            </form>
            {% endif %}

            <div class="row justify-content-center mt-2">
                {% if perms.catalogo.change_obra %}
                <a class="btn btn-warning mx-2 col-2" href="{% url 'editar_obra' obra.id %}">Editar Obra</a>
                {% endif %}
                {% if perms.catalogo.delete_obra %}
                <a class="btn btn-danger mx-2 col-2" href="{% url 'eliminar_obra' obra.id %}">Eliminar Obra</a>
                {% endif %}
            </div>
        </div>
    </div>
    
    <script src="https://unpkg.com/htmx.org@1.9.10"></script>

</section>
{% endblock %}

catalogo/templates/catalogo/editar_obra.html
{% extends 'core/base.html' %}

{% load static %}
{% block contenido %}

{% load crispy_forms_tags %}

<div class="container">
    {% if form.errors %}
        <div class="fs-4 p-3 mb-4 bg-danger rounded-3 shadow-sm text-light">
            {{ form.errors }}
        </div>
    {% endif %}

    <form method="POST"  enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">{{ form.titulo|as_crispy_field }}</div>
        <div class="row">
            <div class="col-8">
                {{ form.imagen|as_crispy_field }}
                <img class="img-fluid" src="{{ obra.imagen_url }}" alt="obra">
            </div>
            <div class="col-4">
                {{ form.medio|as_crispy_field }}
                {{ form.estado|as_crispy_field }}
                {{ form.precio|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-8">{{ form.descripcion|as_crispy_field }}</div>
            <div class="col-4">{{ form.etiquetas|as_crispy_field }}</div>
        </div>
        <button class="btn btn-primary" type="submit">Editar obra</button>
        <a href="{% url 'obra' obra.id %}" class="btn btn-secondary">Volver a la obra</a>
    </form>
</div>

{% endblock %}

catalogo/templates/catalogo/eliminar_obra.html
{% extends 'core/base.html' %}

{% load static %}
{% block contenido %}

<div class="card mt-4">
    <div class="card-body">
        <h4 class="mb-3">Confirmación eliminar obra</h4>
        <p>¿Está seguro/a que desea eliminar esta obra?</p>

        <div class="row mb-3 justify-content-around">
            <img class="img-fluid col-4" src="{{ obra.imagen_url }}" alt="obra">
            <div class="col-7">
                <h2>{{ obra.titulo }} <span class="text-muted fs-4">ID: {{ obra.id }}</span></h2>
                <h3 class="text-primary">Medio: {{ obra.medio }}</h3>
                <h5 class="text-muted">
                    Etiquetas: 
                        {% for e in obra.etiquetas.all %}
                            {{ e.nombre }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                </h5>
                <h4 class="fs-5 mb-4 {% if publicacion.fuente_de_texto == 'oswald' %}oswald{% endif %}">{{ publicacion.descripcion }}</h4>
                <h3 class="text-success">{{ obra.estado }} | Precio: ${{ obra.precio }}</h3>
            </div>
        </div>

        <form method="POST">
            {% csrf_token %}
            <input type="text" name="obra" value="{{ obra.id }}" class="d-none">
            <button class="btn btn-danger">Eliminar</button>
            <a href="{% url 'obra' obra.id %}" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>
</div>

{% endblock %}

catalogo/templates/catalogo/registrar_obra.html
{% extends 'core/base.html' %}

{% load static %}
{% block contenido %}

{% load crispy_forms_tags %}

<div class="container">
    {% if form.errors %}
        <div class="fs-4 p-3 mb-4 bg-danger rounded-3 shadow-sm text-light">
            {{ form.errors }}
        </div>
    {% endif %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">{{ form.titulo|as_crispy_field }}</div>
        <div class="row">
            <div class="col-8">{{ form.imagen|as_crispy_field }}</div>
            <div class="col-4">
                {{ form.medio|as_crispy_field }}
                {{ form.estado|as_crispy_field }}
                {{ form.precio|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-8">{{ form.descripcion|as_crispy_field }}</div>
            <div class="col-4">{{ form.etiquetas|as_crispy_field }}</div>
        </div>
        <button class="btn btn-primary" type="submit">Añadir obra</button>
        <a href="{% url 'catalogo' %}" class="btn btn-secondary">Volver al catálogo</a>
    </form>
</div>

{% endblock %}